name: Build LaTeX Resume
on:
  push:
    paths:
      - 'Shubham_Resume.tex'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          fetch-depth: 0
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Shubham_Resume.tex
          work_in_root_file_dir: true
          extra_system_packages: "texlive-pictures"
      
      - name: Rename output PDF
        run: |
          mv Shubham_Resume.pdf "Shubham Rathod.pdf"
      
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "Shubham Rathod.pdf"
      
      - name: Install ghostscript and imagemagick
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y ghostscript imagemagick
      
      - name: Change ImageMagick security policy
        run: |
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/name="height" value="[^"]*"/name="height" value="128KP"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/name="width" value="[^"]*"/name="width" value="128KP"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/name="area" value="[^"]*"/name="area" value="128MP"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/name="disk" value="[^"]*"/name="disk" value="8GiB"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/name="map" value="[^"]*"/name="map" value="4GiB"/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/name="memory" value="[^"]*"/name="memory" value="2GiB"/' /etc/ImageMagick-6/policy.xml
      
      - name: Convert PDF to PNG
        run: |
          INPUT_PDF="Shubham Rathod.pdf"
          OUTPUT_PNG="resume.png"
          convert -density 900 -background white -alpha off "$INPUT_PDF" -resize 25% -quality 90 -colorspace RGB "$OUTPUT_PNG"
      
      - name: Update README with image
        run: |
          if [ -f README.md ]; then
            if grep -q "!\[Resume\]" README.md; then
              echo "Image already in README, updating timestamp only"
            else
              echo -e "\n## Resume Preview\n\n![Resume](resume.png)\n" >> README.md
            fi
          else
            echo -e "# Shubham Rathod's Resume\n\n![Resume](resume.png)\n" > README.md
          fi
          sed -i '/Last updated:/d' README.md
          echo -e "\nLast updated: $(date '+%B %d, %Y')" >> README.md
      
      - name: Commit changes
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add "Shubham Rathod.pdf" resume.png README.md
          git commit -m "[Automated] Update resume PDF and preview image" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: ${{ github.ref_name }}
